
% Parameter values


p.a=1;       %alpha
p.abar=1;    %alpha bar
p.aprime=1;  %alpha prime


mu = 1;
b = 1; 


m = 10; %mu prime

bb = 1; %beta

e = 0.1; %epsilon
ee = 1;  %epsilon prime

u0a = 0.1;
u01 = 0.1;
u02 = 0.1;

uu1 = 6; %tilde u1
uu2 =6;  %tilde u2
uua = 6; %tilde ua

ax=10;  % px,pz
ex=1;   % epsilonx, epsilonz




% equilibrium point corresponding to the intersection between the two curves generated by the mathematica code

x1=0.912771671114167;
x2= 0.951233023665938;
x3=0.868443766811376;
x4=2.443980581724994;
x5=(ax/ex)*x4;

x6=0.912771671114167;
x7= 0.951233023665938;
x8=0.868443766811376;
x9=2.443980581724994;
x10=(ax/ex)*x9;


%Jacobian


A=[-uu1*x10-(u01+ap*x2)-m*(e*bb + ee*x4), -uu1*x10+ap*(1-x1-x4), uu1*x10, -uu1*x10-(u01+ap*x2)-m*ee*x1, 0,...
   0, 0, 0, 0, uu1*(1 - x1 - x2 + x3 - x4);...
   -uu2*x10+ab*(1-x2-x4), -uu2*x10+a*(1-x2-x4)-(u02+a*x2+ab*x1)-mu*(b*e + ee*x4), uu2*x10, -uu2*x10-(u02+a*x2+ab*x1)-mu*ee*x2, 0,...
   0, 0, 0, 0, uu2*(1 - x1 - x2 + x3 - x4);...
   ab*(x1-x3)+(u02+a*x2+ab*x1), ap*(x2-x3)+(u01+ap*x2)+a*(x1-x3), -(u01+ap*x2)-(u02+a*x2+ab*x1)-(m*(e*bb + ee*x4)+mu*(b*e + ee*x4)), -(mu*ee+m*ee)*x3, 0,...
   0, 0, 0, 0, 0;...
   -(u0a+uua*x5+x4)-ee*x4, -(u0a+uua*x5+x4)-ee*x4, +(u0a+uua*x5+x4), -(u0a+uua*x5+x4)+(1 - x1 - x2 - x3 - x4)-(e+ee*(x1+x2)), uua*(1 - x1 - x2 + x3 - x4),...
   0, 0, 0, 0, 0;...
   0, 0, 0, ax, -ex, 0, 0, 0, 0, 0;...
   0, 0, 0, 0, uu1*(1 - x6 - x7 + x8 - x9),...
   -uu1*x5-(u01+ap*x7)-m*(e*bb + ee*x9), -uu1*x5+ap*(1-x6-x9), uu1*x5, -uu1*x5-(u01+ap*x7)-m*ee*x6, 0;...
   0, 0, 0, 0, uu2*(1 - x6 - x7 + x8 - x9),...
   -uu2*x5+ab*(1-x7-x9), -uu2*x5+a*(1-x7-x9)-(u02+a*x7+ab*x6)-mu*(b*e + ee*x9), uu2*x5, -uu2*x5-(u02+a*x7+ab*x6)-mu*ee*x7, 0;...
   0, 0, 0, 0, 0,...
   ab*(x6-x8)+(u02+a*x7+ab*x6), ap*(x7-x8)+(u01+ap*x7)+a*(x6-x8), -(u01+ap*x7)-(u02+a*x7+ab*x6)-(m*(e*bb + ee*x9)+mu*(b*e + ee*x9)), -(mu*ee+m*ee)*x8, 0;...
   0, 0, 0, 0, 0,...
   -(u0a+uua*x10+x9)-ee*x9, -(u0a+uua*x10+x9)-ee*x9, +(u0a+uua*x10+x9), -(u0a+uua*x10+x9)+(1 - x6 - x7 - x8 - x9)-(e+ee*(x6+x7)), uua*(1 - x6 - x7 + x8 - x9);...   
    0, 0, 0, 0, 0,...
    0, 0, 0, ax, -ex];
   
   
   
   


%eigenvalues


B = eig(A)



